name: lavoauto
description: "A lavoauto project - car washing service app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1

  # Objects comparison
  equatable: ^2.0.3
  
  # Service Locator
  injectable: ^2.3.1

  # Allows easier routing
  auto_route: ^9.2.0

  google_fonts: ^6.2.1

  get_it: ^8.0.1
  # freezed: ^2.4.3
  # freezed_annotation: ^2.4.1
  
  responsive_framework: ^1.4.0
  http: ^1.1.0
  http_parser: ^4.0.2 
  shared_preferences: ^2.2.3
  device_preview: ^1.1.0
  cached_network_image: ^3.4.0
  flutter_dotenv: ^5.0.2
  intl: ^0.20.2
  flutter_native_splash: ^2.3.4
  json_annotation: ^4.9.0
  device_info_plus: ^11.3.0
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  image: ^4.5.4
  path: ^1.9.0
  path_provider: ^2.1.4
  url_launcher: ^6.2.5
  flutter_stripe: ^10.1.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_svg: ^2.2.3
  flutter_switch: ^0.3.2
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator:
  json_serializable:
  auto_route_generator: ^9.0.0
  build_runner: any

flutter_launcher_icons:
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false




flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - .env
